import {Metadata} from "next";

export const metadata = {
  title: {
    default:"Learning Next.Js",
    template:"%s | Nextjs",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header
        style={{
          backgroundColor:"pink",
          padding:"2rem",
        }}
      > Header</header>
        {children}
        <footer
        style={{
          backgroundColor:"purple",
          padding:"2rem",
        }}
      > Footer</footer>
      </body>
    </html>
  )
}
